"""Constants for Neptun Smart integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "neptun_smart_local"

CONF_SLAVE = "slave"
CONF_WIRELESS_SENSORS = "wireless_sensors"
CONF_LEAK_LINES = "leak_lines"

DEFAULT_NAME = "Neptun Smart"
DEFAULT_PORT = 503
DEFAULT_SLAVE = 240
DEFAULT_TIMEOUT = 3
DEFAULT_SCAN_INTERVAL = 10
DEFAULT_WIRELESS_SENSORS = 1
DEFAULT_LEAK_LINES = 1

PLATFORMS = ["sensor", "binary_sensor", "switch", "number"]

COORDINATOR = "coordinator"

UPDATE_INTERVAL_FALLBACK = timedelta(seconds=DEFAULT_SCAN_INTERVAL)

REG_ALARM_MODE = 0
REG_LEAK_SENSOR_RAW = 3
REG_WIRELESS_SENSOR_COUNT = 6
REG_WIRELESS_SENSORS_START = 57
REG_WIRELESS_SENSORS_COUNT = 5
REG_WATER_COUNTERS_START = 107
REG_WATER_COUNTERS_REG_COUNT = 16
REG_COUNTER_SETTINGS_START = 123
REG_COUNTER_SETTINGS_COUNT = 8

BIT_FLOOR_WASHING_MODE = 1 << 0
BIT_ALARM_ZONE_1 = 1 << 1
BIT_ALARM_ZONE_2 = 1 << 2
BIT_BATTERY_DRAIN = 1 << 3
BIT_LOST_CONNECTION = 1 << 4
BIT_WIRELESS_PAIRING = 1 << 7
BIT_ZONE_1 = 1 << 8
BIT_ZONE_2 = 1 << 9
BIT_DUAL_ZONE_MODE = 1 << 10
BIT_CLOSE_TAPS_ON_SENSOR_LOST = 1 << 11
BIT_KEYPAD_LOCKS = 1 << 12

MASK_ZONE_BOTH = BIT_ZONE_1 | BIT_ZONE_2
